image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
    - build

before_script:
    - "git submodule init"
    - "git submodule update"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet publish -c Release"
