// <auto-generated by="the Blazor I18n Text compiler" />
namespace atomex_frontend.I18nText
{
    public partial class Translations : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Address"</summary>
        public string Address;

        /// <summary>"Amount"</summary>
        public string Amount;

        /// <summary>"Available"</summary>
        public string Available;

        /// <summary>"Balance update in progress..."</summary>
        public string BalanceUpdateInProgress;

        /// <summary>"Cancel"</summary>
        public string Cancel;

        /// <summary>"Confirm password:"</summary>
        public string ConfirmPasswordPlaceholder;

        /// <summary>"Conversion"</summary>
        public string Conversion;

        /// <summary>"Convert"</summary>
        public string Convert;

        /// <summary>"Delegate"</summary>
        public string Delegate;

        /// <summary>"Description"</summary>
        public string Description;

        /// <summary>"Do you really want"</summary>
        public string DoYouReallyWant;

        /// <summary>"Wallet name could not be emty"</summary>
        public string EmptyWalletName;

        /// <summary>"Enter password:"</summary>
        public string EnterPasswordPlaceholder;

        /// <summary>"Enter wallet name:"</summary>
        public string EnterWalletName;

        /// <summary>"Wallet with this name already exist"</summary>
        public string ErrorWalletNameExist;

        /// <summary>"Estimated payment fee"</summary>
        public string EstimatedPaymentFee;

        /// <summary>"Estimated price"</summary>
        public string EstimatedPrice;

        /// <summary>"Estimated redeem fee"</summary>
        public string EstimatedRedeemFee;

        /// <summary>"Fee"</summary>
        public string Fee;

        /// <summary>"Finish"</summary>
        public string Finish;

        /// <summary>"From"</summary>
        public string From;

        /// <summary>"Gas limit"</summary>
        public string GasLimit;

        /// <summary>"Gas price"</summary>
        public string GasPrice;

        /// <summary>"Instantly sending of currency."</summary>
        public string InstantlySendingOfCurrency;

        /// <summary>"Invalid password"</summary>
        public string InvalidPassword;

        /// <summary>"Language"</summary>
        public string Language;

        /// <summary>"Fee"</summary>
        public string MinersFee;

        /// <summary>"Next"</summary>
        public string Next;

        /// <summary>"NoDelegationsFound"</summary>
        public string NoDelegationsFound;

        /// <summary>"Passwords could not be empty"</summary>
        public string PasswordEmpty;

        /// <summary>"Passwords mismatch"</summary>
        public string PasswordMismatchError;

        /// <summary>"Create at least &quot;Meduim&quot; strongness password"</summary>
        public string PasswordWeak;

        /// <summary>"Portfolio"</summary>
        public string Portfolio;

        /// <summary>"Previous"</summary>
        public string Previous;

        /// <summary>"Receive"</summary>
        public string Receive;

        /// <summary>"Received"</summary>
        public string Recevived;

        /// <summary>"Please select your wallet type."</summary>
        public string RegisterStep1Description;

        /// <summary>"Step 1: Wallet type"</summary>
        public string RegisterStep1Title;

        /// <summary>"Please enter a name for your wallet."</summary>
        public string RegisterStep2Description;

        /// <summary>"Step 2: Wallet name"</summary>
        public string RegisterStep2Title;

        /// <summary>"Mnemonic phrase is used to restore your wallet if the data on your device has been lost. Please, write it down and keep in in safe place."</summary>
        public string RegisterStep3Description;

        /// <summary>"Step 3: Mnemonic phrase"</summary>
        public string RegisterStep3Title;

        /// <summary>"This password can be used for secret key additional protection. To restore a secret key, you will need to enter a mnemonic phrase and this password."</summary>
        public string RegisterStep4Description;

        /// <summary>"Step 4: Derived key password (optional)"</summary>
        public string RegisterStep4Title;

        /// <summary>"This password is used to protect the stored secret keys and will be needed every time you start youe wallet application."</summary>
        public string RegisterStep5Description;

        /// <summary>"Step 5: Storage password"</summary>
        public string RegisterStep5Title;

        /// <summary>"Send"</summary>
        public string Send;

        /// <summary>"Send confirmation"</summary>
        public string SendConfirmation;

        /// <summary>"Sending"</summary>
        public string Sending;

        /// <summary>"Sending was successfull"</summary>
        public string SendingWasSuccessfull;

        /// <summary>"Sent"</summary>
        public string Sent;

        /// <summary>"State"</summary>
        public string State;

        /// <summary>"Success"</summary>
        public string Success;

        /// <summary>"Swap redeem"</summary>
        public string SwapRedeem;

        /// <summary>"Time"</summary>
        public string Time;

        /// <summary>"To"</summary>
        public string To;

        /// <summary>"To Address"</summary>
        public string ToAddress;

        /// <summary>"Total fee"</summary>
        public string TotalFee;

        /// <summary>"Type"</summary>
        public string Type;

        /// <summary>"Unlock"</summary>
        public string Unlock;

        /// <summary>"Upadte"</summary>
        public string Update;

        /// <summary>"Use default fee"</summary>
        public string UseDefaultFee;

        /// <summary>"Wallets"</summary>
        public string Wallets;

        /// <summary>"Word count"</summary>
        public string WordCount;
    }
}
