// <auto-generated by="the Blazor I18n Text compiler" />
namespace atomex_frontend.I18nText
{
    public partial class Translations : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Cancel"</summary>
        public string Cancel;

        /// <summary>"Confirm password:"</summary>
        public string ConfirmPasswordPlaceholder;

        /// <summary>"Wallet name could not be emty"</summary>
        public string EmptyWalletName;

        /// <summary>"Enter password:"</summary>
        public string EnterPasswordPlaceholder;

        /// <summary>"Enter wallet name:"</summary>
        public string EnterWalletName;

        /// <summary>"Wallet with this name already exist"</summary>
        public string ErrorWalletNameExist;

        /// <summary>"Finish"</summary>
        public string Finish;

        /// <summary>"Invalid password"</summary>
        public string InvalidPassword;

        /// <summary>"Language"</summary>
        public string Language;

        /// <summary>"Next"</summary>
        public string Next;

        /// <summary>"Passwords could not be empty"</summary>
        public string PasswordEmpty;

        /// <summary>"Passwords mismatch"</summary>
        public string PasswordMismatchError;

        /// <summary>"Create at least &quot;Meduim&quot; strongness password"</summary>
        public string PasswordWeak;

        /// <summary>"Previous"</summary>
        public string Previous;

        /// <summary>"Please select your wallet type."</summary>
        public string RegisterStep1Description;

        /// <summary>"Step 1: Wallet type"</summary>
        public string RegisterStep1Title;

        /// <summary>"Please enter a name for your wallet."</summary>
        public string RegisterStep2Description;

        /// <summary>"Step 2: Wallet name"</summary>
        public string RegisterStep2Title;

        /// <summary>"Mnemonic phrase is used to restore your wallet if the data on your device has been lost. Please, write it down and keep in in safe place."</summary>
        public string RegisterStep3Description;

        /// <summary>"Step 3: Mnemonic phrase"</summary>
        public string RegisterStep3Title;

        /// <summary>"This password can be used for secret key additional protection. To restore a secret key, you will need to enter a mnemonic phrase and this password."</summary>
        public string RegisterStep4Description;

        /// <summary>"Step 4: Derived key password (optional)"</summary>
        public string RegisterStep4Title;

        /// <summary>"This password is used to protect the stored secret keys and will be needed every time you start youe wallet application."</summary>
        public string RegisterStep5Description;

        /// <summary>"Step 5: Storage password"</summary>
        public string RegisterStep5Title;

        /// <summary>"Unlock"</summary>
        public string Unlock;

        /// <summary>"Word count"</summary>
        public string WordCount;
    }
}
