// <auto-generated by="the Blazor I18n Text compiler" />
namespace atomex_frontend.I18nText
{
    public partial class Translations : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"You have active swaps. Closing the application or sign out may result in loss of funds as a result of the failure of the refund or redeem operations."</summary>
        public string ActiveSwapsWarning;

        /// <summary>"Address"</summary>
        public string Address;

        /// <summary>"Addresses"</summary>
        public string Addresses;

        /// <summary>"{0} successfully updated."</summary>
        public string AddressUpdated;

        /// <summary>"Already delegated"</summary>
        public string AlreadyDelagated;

        /// <summary>"Amount"</summary>
        public string Amount;

        /// <summary>"Autofill delegation error. Try again later"</summary>
        public string AutofillDelegationError;

        /// <summary>"Autofill transaction failed"</summary>
        public string AutofillTxFailed;

        /// <summary>"Available"</summary>
        public string Available;

        /// <summary>"Baker is deactivated. Pick another one"</summary>
        public string BakerDeactivated;

        /// <summary>"Warning: the selected baker has a minimum delegation limit, which exceeds the balance of your selected wallet"</summary>
        public string BakerHasMinDelegateLimit;

        /// <summary>"Balance update in progress..."</summary>
        public string BalanceUpdateInProgress;

        /// <summary>"Cancel"</summary>
        public string Cancel;

        /// <summary>"Can not convert"</summary>
        public string CantConvert;

        /// <summary>"Can&apos;t get tezos currency"</summary>
        public string CantGetTezos;

        /// <summary>"Confirm password:"</summary>
        public string ConfirmPasswordPlaceholder;

        /// <summary>"Conversion"</summary>
        public string Conversion;

        /// <summary>"Convert"</summary>
        public string Convert;

        /// <summary>"Convert confirmation"</summary>
        public string ConvertConfirmation;

        /// <summary>"Converting"</summary>
        public string Converting;

        /// <summary>"Converting error"</summary>
        public string ConvertingError;

        /// <summary>"Copy"</summary>
        public string Copy;

        /// <summary>"Copying the private key to the clipboard may result in the loss of all your coins in the wallet. Are you sure you want to copy the private key for {0}?"</summary>
        public string CopyPrivateAddrWarning;

        /// <summary>"Conversion error. Please contant technical support"</summary>
        public string CvConversionError;

        /// <summary>"Error"</summary>
        public string CvError;

        /// <summary>"Insufficient {0} to cover token transfer fee"</summary>
        public string CvInsufficientChainFunds;

        /// <summary>"Insufficient funds"</summary>
        public string CvInsufficientFunds;

        /// <summary>"Warning: too low fees"</summary>
        public string CvLowFees;

        /// <summary>"The amount must be greater than or equal to the minimum allowed amount {0} {1"</summary>
        public string CvMinimumAllowedQtyWarning;

        /// <summary>"Not enough liquidity to convert a specified amount"</summary>
        public string CvNoLiquidity;

        /// <summary>"This symbol does not support direct conversion"</summary>
        public string CvNotSupportedSymbol;

        /// <summary>"Standard"</summary>
        public string CvOrderTypeStandard;

        /// <summary>"Standard With Fixed Fee"</summary>
        public string CvOrderTypeStandardWithFixedFee;

        /// <summary>"Atomex services unavailable. Please check your network connection or contact technical support"</summary>
        public string CvServicesUnavailable;

        /// <summary>"Wallet locked. Please unlock the wallet to continue"</summary>
        public string CvWalletLocked;

        /// <summary>"Warning"</summary>
        public string CvWarning;

        /// <summary>"Amount to convert must be greater than zero"</summary>
        public string CvWrongAmount;

        /// <summary>"Back"</summary>
        public string CwvBack;

        /// <summary>"Cancel"</summary>
        public string CwvCancel;

        /// <summary>"Generate and write down the mnemonic before continuing"</summary>
        public string CwvCreateMnemonicWarning;

        /// <summary>"Wallet name must be not empty"</summary>
        public string CwvEmptyWalletName;

        /// <summary>"Finish"</summary>
        public string CwvFinish;

        /// <summary>"Invalid wallet name"</summary>
        public string CwvInvalidWalletName;

        /// <summary>"Invalid mnemonic phrase"</summary>
        public string CwvMnemonicInvalidError;

        /// <summary>"Word count should be 12,15,18,21 or 24"</summary>
        public string CwvMnemonicInvalidWordcountError;

        /// <summary>"Word {0} is not in the wordlist for this language"</summary>
        public string CwvMnemonicInvalidWordError;

        /// <summary>"Mnemonic phrase can not be empty"</summary>
        public string CwvMnemonicIsEmptyError;

        /// <summary>"Next"</summary>
        public string CwvNext;

        /// <summary>"Password has insufficient complexity"</summary>
        public string CwvPasswordInsufficientComplexity;

        /// <summary>"Passwords do not match"</summary>
        public string CwvPasswordsDoNotMatch;

        /// <summary>"Scan"</summary>
        public string CwvScan;

        /// <summary>"Scan All"</summary>
        public string CwvScanAll;

        /// <summary>"Wallet with the same name already exists"</summary>
        public string CwvWalletAlreadyExists;

        /// <summary>"Delegate"</summary>
        public string Delegate;

        /// <summary>"Delegating"</summary>
        public string Delegating;

        /// <summary>"Delegating to a bakery"</summary>
        public string DelegatingToABakery;

        /// <summary>"Delegation confirmation"</summary>
        public string DelegationConfirmation;

        /// <summary>"An error has occurred while delegation"</summary>
        public string DelegationError;

        /// <summary>"Description"</summary>
        public string Description;

        /// <summary>"Do you really want"</summary>
        public string DoYouReallyWant;

        /// <summary>"Do you really want to convert"</summary>
        public string DoYouReallyWantToConvert;

        /// <summary>"Do you really want to delegate"</summary>
        public string DoYouReallyWantToDelegate;

        /// <summary>"Wallet name could not be emty"</summary>
        public string EmptyWalletName;

        /// <summary>"Enter password:"</summary>
        public string EnterPasswordPlaceholder;

        /// <summary>"Enter wallet name:"</summary>
        public string EnterWalletName;

        /// <summary>"Error"</summary>
        public string Error;

        /// <summary>"Wallet with this name already exist"</summary>
        public string ErrorWalletNameExist;

        /// <summary>"Estimated payment fee"</summary>
        public string EstimatedPaymentFee;

        /// <summary>"Estimated price"</summary>
        public string EstimatedPrice;

        /// <summary>"Estimated redeem fee"</summary>
        public string EstimatedRedeemFee;

        /// <summary>"Fee"</summary>
        public string Fee;

        /// <summary>"Fee Rate"</summary>
        public string FeeRate;

        /// <summary>"Finish"</summary>
        public string Finish;

        /// <summary>"From"</summary>
        public string From;

        /// <summary>"Full"</summary>
        public string Full;

        /// <summary>"Gas limit"</summary>
        public string GasLimit;

        /// <summary>"Gas price"</summary>
        public string GasPrice;

        /// <summary>"Instantly sending of currency."</summary>
        public string InstantlySendingOfCurrency;

        /// <summary>"Invalid mnemonic phrase."</summary>
        public string InvalidMnemonic;

        /// <summary>"Word count should be 12,15,18,21 or 24."</summary>
        public string InvalidMnemonicWordCount;

        /// <summary>"Invalid password"</summary>
        public string InvalidPassword;

        /// <summary>"Word {0} is not in the wordlist for this language."</summary>
        public string IsNotInTheWorldList;

        /// <summary>"Language"</summary>
        public string Language;

        /// <summary>"Loading"</summary>
        public string Loading;

        /// <summary>"Fee"</summary>
        public string MinersFee;

        /// <summary>"Mnemonic phrase could not be empty"</summary>
        public string MnemonicCouldNotBeEmpty;

        /// <summary>"Mnemonic phrase"</summary>
        public string MnemonicPhras;

        /// <summary>"Mnemonic phrase"</summary>
        public string MnemonicPhrase;

        /// <summary>"Next"</summary>
        public string Next;

        /// <summary>"No"</summary>
        public string No;

        /// <summary>"No delegations found"</summary>
        public string NoDelegationsFound;

        /// <summary>"You don&apos;t have non-empty accounts"</summary>
        public string NoEmptyAccounts;

        /// <summary>"No liquidity"</summary>
        public string NoLiquidity;

        /// <summary>"Note: this baker is overdelegated, it will be better to choose another"</summary>
        public string OverdelegatedNote;

        /// <summary>"Passwords could not be empty"</summary>
        public string PasswordEmpty;

        /// <summary>"Passwords mismatch"</summary>
        public string PasswordMismatchError;

        /// <summary>"Create at least &quot;Meduim&quot; strongness password"</summary>
        public string PasswordWeak;

        /// <summary>"Portfolio"</summary>
        public string Portfolio;

        /// <summary>"Previous"</summary>
        public string Previous;

        /// <summary>"Private key for {0} successfully copied to clipboard."</summary>
        public string PrivKeyCopied;

        /// <summary>"No tokens"</summary>
        public string PwNoTokens;

        /// <summary>"Receive"</summary>
        public string Receive;

        /// <summary>"Received"</summary>
        public string Recevived;

        /// <summary>"Please select your wallet type."</summary>
        public string RegisterStep1Description;

        /// <summary>"Шаг 1: Тип кошелька"</summary>
        public string RegisterStep1Title;

        /// <summary>"Please enter a name for your wallet."</summary>
        public string RegisterStep2Description;

        /// <summary>"Шаг 2: Название кошелька"</summary>
        public string RegisterStep2Title;

        /// <summary>"Mnemonic phrase is used to restore your wallet if the data on your device has been lost. Please, write it down and keep in safe place."</summary>
        public string RegisterStep3Description;

        /// <summary>"Step 3: Mnemonic phrase"</summary>
        public string RegisterStep3Title;

        /// <summary>"This is your mnemonic phrase words in random order. Please re-arrange words to their original order by clicking and drag&apos;n&apos;drop."</summary>
        public string RegisterStep4Description;

        /// <summary>"Step 4: Mnemonic phrase confirmation"</summary>
        public string RegisterStep4Title;

        /// <summary>"This password can be used for secret key additional protection. To restore a secret key, you will need to enter a mnemonic phrase and this password."</summary>
        public string RegisterStep5Description;

        /// <summary>"Step 5: Derived key password (optional)"</summary>
        public string RegisterStep5Title;

        /// <summary>"This password is used to protect the stored secret keys and will be needed every time you start your wallet application."</summary>
        public string RegisterStep6Description;

        /// <summary>"Step 6: Storage password"</summary>
        public string RegisterStep6Title;

        /// <summary>"Restore"</summary>
        public string Restore;

        /// <summary>"Please select your wallet type."</summary>
        public string RestoreStep1Description;

        /// <summary>"Please enter a name for your wallet."</summary>
        public string RestoreStep2Description;

        /// <summary>"Please enter a mnemonic phrase for your wallet:"</summary>
        public string RestoreStep3Description;

        /// <summary>"If you used a password to additioonal protect the secret key, please enter it in the box below. If you enter the wrong password, you will not be able to access your secret key and wallet."</summary>
        public string RestoreStep4Description;

        /// <summary>"This password is used to protect the stored secret keys and will be needed every time you start your wallet application."</summary>
        public string RestoreStep5Description;

        /// <summary>"Send"</summary>
        public string Send;

        /// <summary>"Send confirmation"</summary>
        public string SendConfirmation;

        /// <summary>"Sending"</summary>
        public string Sending;

        /// <summary>"Sending was successfull"</summary>
        public string SendingWasSuccessfull;

        /// <summary>"Sent"</summary>
        public string Sent;

        /// <summary>"SignOut"</summary>
        public string Signout;

        /// <summary>"State"</summary>
        public string State;

        /// <summary>"Success"</summary>
        public string Success;

        /// <summary>"Successfull delegation"</summary>
        public string SuccessfullDelegation;

        /// <summary>"Amount must be greater than zero"</summary>
        public string SvAmountLessThanZeroError;

        /// <summary>"The transfer amount {0} with estimated commission {1} exceeds the amount of available funds"</summary>
        public string SvAvailableFundsDetailedError;

        /// <summary>"The transfer amount (including commission) exceeds the amount of available funds"</summary>
        public string SvAvailableFundsError;

        /// <summary>"Back"</summary>
        public string SvBack;

        /// <summary>"Cancel"</summary>
        public string SvCancel;

        /// <summary>"Commission must be a positive value"</summary>
        public string SvCommissionLessThanZeroError;

        /// <summary>"Address must be not empty"</summary>
        public string SvEmptyAddressError;

        /// <summary>"Error"</summary>
        public string SvError;

        /// <summary>"Failed"</summary>
        public string SvFailed;

        /// <summary>"Gas limit"</summary>
        public string SvGasLimit;

        /// <summary>"Insufficient funds for default fee"</summary>
        public string SvInsufficientFundsForDefaultFeeError;

        /// <summary>"Address is invalid"</summary>
        public string SvInvalidAddressError;

        /// <summary>"Mining fee"</summary>
        public string SvMiningFee;

        /// <summary>"No"</summary>
        public string SvNo;

        /// <summary>"Ok"</summary>
        public string SvOk;

        /// <summary>"NOTE: Do not sign out or close the application until the swap is completed, otherwise it may result in a loss of funds."</summary>
        public string SvOrderMatched;

        /// <summary>"Order rejected"</summary>
        public string SvOrderRejected;

        /// <summary>"Oops, the price has changed during the order sending. Please try again"</summary>
        public string SvPriceHasChanged;

        /// <summary>"Send"</summary>
        public string SvSend;

        /// <summary>"Send Confirmation"</summary>
        public string SvSendConfirmation;

        /// <summary>"Sending"</summary>
        public string SvSending;

        /// <summary>"Success"</summary>
        public string SvSuccess;

        /// <summary>"Atomex is not responding for a long time"</summary>
        public string SvTimeoutReached;

        /// <summary>"Yes"</summary>
        public string SvYes;

        /// <summary>"NOTE: Do not sign out or close the application until the swap is completed, otherwise it may result in a loss of funds."</summary>
        public string SwapNote;

        /// <summary>"Swap redeem"</summary>
        public string SwapRedeem;

        /// <summary>"Swap request successfully created. Please wait a moment until the swap begins. Do not sign out or close the application until the swap begins."</summary>
        public string SwapRequestCreated;

        /// <summary>"Swap successfully created."</summary>
        public string SwapSuccessfullyCreated;

        /// <summary>"Time"</summary>
        public string Time;

        /// <summary>"To"</summary>
        public string To;

        /// <summary>"To Address"</summary>
        public string ToAddress;

        /// <summary>"Total fee"</summary>
        public string TotalFee;

        /// <summary>"Transaction signing error"</summary>
        public string TxSigningError;

        /// <summary>"Type"</summary>
        public string Type;

        /// <summary>"Unlock"</summary>
        public string Unlock;

        /// <summary>"Update"</summary>
        public string Update;

        /// <summary>"Restoring wallet data, please wait..."</summary>
        public string UpdatingPortfolioTitle;

        /// <summary>"Use default fee"</summary>
        public string UseDefaultFee;

        /// <summary>"Wallets"</summary>
        public string Wallets;

        /// <summary>"Warning"</summary>
        public string Warning;

        /// <summary>"with payment fee"</summary>
        public string WithPaymentFee;

        /// <summary>"with price"</summary>
        public string WithPrice;

        /// <summary>"with redeem fee"</summary>
        public string WithRedeemFee;

        /// <summary>"Word count"</summary>
        public string WordCount;

        /// <summary>"Wrong delegation address"</summary>
        public string WrongDelegationAddress;

        /// <summary>"Yes"</summary>
        public string Yes;
    }
}
