name: .NET Core CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.401

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release

      - name: Upload result files
        uses: actions/upload-artifact@v2
        with:
          name: atomex
          path: bin/Release/netstandard2.1/publish/wwwroot

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download build files
        uses: actions/download-artifact@v2
        with:
          name: atomex

      - name: Delete old files on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /home/${{ secrets.USERNAME }}/dump
            mkdir -p wwwroot
            mv /home/${{ secrets.USERNAME }}/wwwroot /home/${{ secrets.USERNAME }}/dump

      - name: Copy static files on Atomex server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: '.'
          target: 'wwwroot'
          rm: true

      - name: Copy new build files to nginx dir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /home/${{ secrets.USERNAME }}/wallet.atomex.me
            cp -r /home/${{ secrets.USERNAME }}/wwwroot /home/${{ secrets.USERNAME }}/wallet.atomex.me
